version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=jobapp
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  pg-admin:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - '8081:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin